Repository Axway/amplify-central, pull requests merged in 2022-01, with the labels that each got.

#66 Create page in Integrate with Amplify Central section “query-the-traceability-apis-with-lexus”
  content/en/docs/integrate_with_central/query-the-traceability-apis-with-lexus.md
Labels: question, netlify-cms/pending_review

#72 Update page in Connect API Manager section “agent-variables”
  content/en/docs/connect_manage_environ/connect_api_manager/agent-variables.md
Labels: netlify-cms/pending_review

#73 Update page in Connect API Manager section “agent-variables”
  content/en/docs/connect_manage_environ/connect_api_manager/agent-variables.md
Labels: netlify-cms/pending_publish
